name: Presubmit Go

on:
  pull_request:
    branches:
    - main
    paths:
    - '**.go'
    - go.mod
    - go.sum
    - scripts/presubmit_go.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Go Setup
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Go Presubmit
      run: ./scripts/presubmit_go.sh
